import { useEffect, useState } from 'react';
import { getFallbackData } from '../githubFallback';

// GitHub Stats Hook - Optimized with fallback data and long-term caching
function useGitHubStats(username) {
  // Load fallback data immediately to avoid "..." placeholders
  const fallbackData = getFallbackData(username);
  const cacheKey = username ? `github_stats_${username}` : null;
  const cached = cacheKey ? localStorage.getItem(cacheKey) : null;
  let cachedData = null;
  if (cached) {
    try {
      const parsed = JSON.parse(cached);
      cachedData = parsed?.data || null;
    } catch {
      if (cacheKey) localStorage.removeItem(cacheKey);
    }
  }

  const [stats, setStats] = useState(cachedData?.stats || fallbackData?.stats || null);
  const [repos, setRepos] = useState(cachedData?.repos || fallbackData?.repos || []);
  const [loading, setLoading] = useState(false); // Start as false since we have fallback
  const [linesOfCode, setLinesOfCode] = useState(cachedData?.linesOfCode || fallbackData?.linesOfCode || null);

  // GitHub token from environment variable (increases rate limit from 60 to 5000 requests/hour)
  const githubToken = import.meta.env.VITE_GITHUB_TOKEN;
  const headers = githubToken ? { Authorization: 'token ' + githubToken } : {};

  useEffect(() => {
    if (!username || username === 'YOUR_GITHUB_USERNAME') {
      setLoading(false);
      return;
    }

    const cacheKey = `github_stats_${username}`;
    const cached = localStorage.getItem(cacheKey);
    let parsedCache = null;
    if (cached) {
      try {
        parsedCache = JSON.parse(cached);
        if (parsedCache?.data) {
          setStats(parsedCache.data.stats);
          setRepos(parsedCache.data.repos);
          setLinesOfCode(parsedCache.data.linesOfCode);
        }
      } catch {
        localStorage.removeItem(cacheKey);
      }
    }

    const TWELVE_HOURS_MS = 12 * 60 * 60 * 1000;
    const cacheAgeMs = parsedCache?.timestamp ? Date.now() - parsedCache.timestamp : null;
    const cacheIsFresh = typeof cacheAgeMs === 'number' ? cacheAgeMs < TWELVE_HOURS_MS : false;
    if (cacheIsFresh) {
      setLoading(false);
      return;
    }

    async function fetchData() {
      try {
        if (!parsedCache?.data) {
          setLoading(true);
        }
        const isProd = import.meta.env.PROD;

        // Production: fetch the static JSON generated by GitHub Actions.
        // Dev: also use the static JSON by default; optionally use direct API fetch
        // if VITE_GITHUB_TOKEN is set.
        const canUseLiveApi = !isProd && Boolean(import.meta.env.VITE_GITHUB_TOKEN);

        if (!canUseLiveApi) {
          const res = await fetch('/github-stats.json', { cache: 'no-store' });
          if (!res.ok) {
            return;
          }
          const json = await res.json();
          if (json?.username && json.username.toLowerCase() !== username.toLowerCase()) {
            return;
          }
          const nextStats = json?.stats || null;
          const nextRepos = json?.repos || [];
          const nextLoc = json?.linesOfCode || null;

          setStats(nextStats);
          setRepos(nextRepos);
          setLinesOfCode(nextLoc);

          localStorage.setItem(
            cacheKey,
            JSON.stringify({
              data: {
                stats: nextStats,
                repos: nextRepos,
                linesOfCode: nextLoc,
              },
              timestamp: Date.now(),
            })
          );
          return;
        }

        // Dev-only live API fetch (requires VITE_GITHUB_TOKEN)
        const [userRes, allReposRes] = await Promise.all([
          fetch(`https://api.github.com/users/${username}`, { headers }),
          fetch(`https://api.github.com/users/${username}/repos?sort=updated&per_page=100`, { headers }),
        ]);

        if (!userRes.ok) {
          return;
        }

        const [userData, allReposData] = await Promise.all([userRes.json(), allReposRes.json()]);

        // Get top 6 repos for display and fetch their languages
        const top6Repos = allReposData.slice(0, 6);
        const displayRepos = await Promise.all(
          top6Repos.map(async (repo) => {
            try {
              const langRes = await fetch(`https://api.github.com/repos/${username}/${repo.name}/languages`, { headers });
              const languages = langRes.ok ? await langRes.json() : {};
              return { ...repo, languages };
            } catch {
              return { ...repo, languages: {} };
            }
          })
        );

        const statsData = {
          publicRepos: userData.public_repos,
          followers: userData.followers,
        };

        setStats(statsData);
        setRepos(displayRepos);

        const linesData = parsedCache?.data?.linesOfCode || fallbackData?.linesOfCode || null;
        setLinesOfCode(linesData);

        // Cache the results in localStorage for 12 hours
        localStorage.setItem(
          cacheKey,
          JSON.stringify({
            data: {
              stats: statsData,
              repos: displayRepos,
              linesOfCode: linesData,
            },
            timestamp: Date.now(),
          })
        );
      } catch {
        // Silently handle GitHub API errors
      } finally {
        setLoading(false);
      }
    }

    fetchData();
  }, [username]);

  return { stats, repos, loading, linesOfCode };
}

export default useGitHubStats;
